# yield estimation by using LinearRegression

# data analysis

In [1]:
import pandas as  pd
df=pd.read_csv("train.csv")
df.head()
df1=pd.read_csv("test.csv")

In [2]:
df.head()

   id  clonesize  honeybee  bumbles  ...  fruitset  fruitmass      seeds       yield
0   0       25.0      0.50     0.25  ...  0.425011   0.417545  32.460887  4476.81146
1   1       25.0      0.50     0.25  ...  0.444908   0.422051  33.858317  5548.12201
2   2       12.5      0.25     0.25  ...  0.552927   0.470853  38.341781  6869.77760
3   3       12.5      0.25     0.25  ...  0.565976   0.478137  39.467561  6880.77590
4   4       25.0      0.50     0.25  ...  0.579677   0.494165  40.484512  7479.93417

[5 rows x 18 columns]

In [3]:
df1.head()

      id  clonesize  honeybee  ...  fruitset  fruitmass      seeds
0  15289       25.0      0.25  ...  0.399367   0.408088  31.394569
1  15290       12.5      0.25  ...  0.488048   0.442866  36.846956
2  15291       12.5      0.25  ...  0.583379   0.487057  40.037644
3  15292       25.0      0.50  ...  0.433014   0.422847  33.116091
4  15293       37.5      0.75  ...  0.360996   0.388860  29.558019

[5 rows x 17 columns]

In [4]:
df=df.drop("id",axis=1)
df1=df1.drop("id",axis=1)

In [5]:
df.corr(numeric_only=True)

                      clonesize  honeybee  ...     seeds     yield
clonesize              1.000000  0.304130  ... -0.396898 -0.382619
honeybee               0.304130  1.000000  ... -0.139261 -0.118001
bumbles                0.080433 -0.017937  ...  0.177022  0.161145
andrena                0.065131  0.030671  ...  0.063504  0.073969
osmia                 -0.007607 -0.010394  ...  0.200597  0.198264
MaxOfUpperTRange       0.016159  0.005840  ...  0.060963 -0.022517
MinOfUpperTRange       0.015838  0.005755  ...  0.061812 -0.021929
AverageOfUpperTRange   0.016057  0.005892  ...  0.062082 -0.021940
MaxOfLowerTRange       0.016343  0.005942  ...  0.061378 -0.022197
MinOfLowerTRange       0.016026  0.005809  ...  0.061360 -0.022319
AverageOfLowerTRange   0.015987  0.005485  ...  0.061853 -0.022081
RainingDays            0.165770  0.046494  ... -0.478818 -0.477191
AverageRainingDays     0.164823  0.037532  ... -0.484439 -0.483870
fruitset              -0.406793 -0.120492  ...  0.929654  0.885967
fruitmass             -0.377688 -0.135310  ...  0.931646  0.826481
seeds                 -0.396898 -0.139261  ...  1.000000  0.868853
yield                 -0.382619 -0.118001  ...  0.868853  1.000000

[17 rows x 17 columns]

In [6]:
l=[]
for i in df.corr(numeric_only=True):
    if -0.1<df.corr(numeric_only=True)[i][16]<0.1:
        l.append(i)






df=df.drop(l,axis=1)

C:\Users\yso05\AppData\Local\Temp\ipykernel_27588\3893273160.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if -0.1<df.corr(numeric_only=True)[i][16]<0.1:

In [7]:
l=[]
for i in df1.columns:
    if i not in df.columns:
        l.append(i)


df1=df1.drop(l,axis=1)

In [8]:
x=df.drop("yield",axis=1)

In [9]:
y=df[["yield"]]

# model training part

In [10]:
from sklearn.linear_model import LinearRegression

In [11]:
lr=LinearRegression()

In [12]:
from sklearn.model_selection import train_test_split

In [13]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=.2,random_state=42)

In [14]:
model1=lr.fit(x_train,y_train)
pred=model1.predict(x_test)

In [15]:
from sklearn.metrics import r2_score

In [16]:
r2_score(pred,y_test)

0.7651912845415071

# we estimated by .76

In [17]:
lr=LinearRegression()

In [18]:
model=lr.fit(x,y)

In [19]:
pre=model.predict(df1)

In [20]:
df2=pd.read_csv("test.csv")

In [21]:
df2["yield"]=pre

In [22]:
df2=df2[["id","yield"]]

In [23]:
df2.to_csv("data.csv",index=False)